spring:
  application:
    name: ledgerlink-service
  datasource:
    url: jdbc:h2:mem:ledgerlink;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    com.ledgerlink: INFO
